#!/bin/bash -e

# Sync latest .ctt configuration files with the top-level template
# and verify the generated template works correctly

CTT_DIR=".ctt/default"

echo "==> Syncing configuration files..."
cp "$CTT_DIR/.editorconfig" go_template/.editorconfig

# This repo runs the same commitizen bump workflow it ships, so the root copy is
# regenerated from the render rather than hand-edited alongside the jinja source.
{
  echo "# Generated by sync_with_ctt.sh from"
  echo "# go_template/.github/workflows/bump_version.yml.jinja - edit that file, not this one."
  cat "$CTT_DIR/.github/workflows/bump_version.yml"
} >.github/workflows/bump_version.yml

echo "==> Installing tools in $CTT_DIR..."
(cd "$CTT_DIR" && mise install)

echo "==> Running CI checks in $CTT_DIR..."
(cd "$CTT_DIR" && mise run ci)

echo "==> Running linter in $CTT_DIR..."
(cd "$CTT_DIR" && mise run lint)

echo ""
echo "All checks passed!"
echo ""
echo "FYI: Occasionally sync the pre-commit config, but requires manual review:"
echo "  cp $CTT_DIR/.pre-commit-config.yaml .pre-commit-config.yaml"
echo "and sync updated versions in reverse:"
echo "  cp .pre-commit-config.yaml go_template/.pre-commit-config.yaml.jinja"
