#!/bin/bash -e

# Sync latest .ctt configuration files with the top-level template
# and verify the generated template works correctly

CTT_DIR=".ctt/default"

# The renders below are deleted with a relative glob, so run from the template
# root or not at all.
cd "$(dirname "$(realpath "$0")")"
if [ ! -f ctt.toml ] || [ ! -d go_template ]; then
    echo "Refusing to run: $PWD is not the template root" >&2
    exit 1
fi

# An in-place `ctt` run reuses each render's recorded .copier-answers.yml and never
# rewrites _skip_if_exists files, so parts of the committed output freeze at
# whatever the template shipped when the directory was first created.
echo "==> Regenerating renders from scratch..."
rm -rf .ctt/*/
uvx --from copier-template-tester ctt

echo "==> Syncing configuration files..."
cp "$CTT_DIR/.editorconfig" go_template/.editorconfig

# This repo runs the same commitizen bump workflow it ships, so the root copy is
# regenerated from a render rather than hand-edited alongside the jinja source.
# The no_goreleaser variant is the right source: this repo has no Go module, so
# the use_goreleaser branch of that workflow would have nothing to build.
{
  echo "# Generated by sync_with_ctt.sh from"
  echo "# go_template/.github/workflows/bump_version.yml.jinja - edit that file, not this one."
  cat ".ctt/no_goreleaser/.github/workflows/bump_version.yml"
} >.github/workflows/bump_version.yml

echo "==> Installing tools in $CTT_DIR..."
(cd "$CTT_DIR" && mise install)

echo "==> Running CI checks in $CTT_DIR..."
(cd "$CTT_DIR" && mise run ci)

echo "==> Running linter in $CTT_DIR..."
(cd "$CTT_DIR" && mise run lint)

echo ""
echo "All checks passed!"
