[tools]
actionlint = "latest"
go = "latest"
"go:github.com/golangci/golines" = "latest"
"golangci-lint" = "2.12.2"
hk = "1.49.0"
ls-lint = "latest"
"pipx:commitizen" = "latest"
"pipx:pre-commit-hooks" = "latest"
"pipx:toml-sort" = "latest"
