[tools]
actionlint = "latest"
go = "latest"
"go:github.com/golangci/golines" = "latest"
"golangci-lint" = "2.12.2"
hk = "1.53.0"
ls-lint = "latest"
"pipx:commitizen" = "latest"
pkl = "latest"
tombi = "latest"
