# typed: false
# frozen_string_literal: true

# Homebrew formula for test-template
# Install: brew install --formula ./Formula/test-template.rb
# Update SHA256 values after each release using:
#   shasum -a 256 test-template-darwin-*

class TestTemplate < Formula
  desc "Generated by copier-template-tester"
  homepage "https://github.com/kyleking/test-template"
  license "MIT"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kyleking/test-template/releases/download/v#{version}/test-template-darwin-arm64"
      sha256 "REPLACE_WITH_SHA256_FOR_DARWIN_ARM64"
    else
      url "https://github.com/kyleking/test-template/releases/download/v#{version}/test-template-darwin-amd64"
      sha256 "REPLACE_WITH_SHA256_FOR_DARWIN_AMD64"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/kyleking/test-template/releases/download/v#{version}/test-template-linux-arm64"
      sha256 "REPLACE_WITH_SHA256_FOR_LINUX_ARM64"
    else
      url "https://github.com/kyleking/test-template/releases/download/v#{version}/test-template-linux-amd64"
      sha256 "REPLACE_WITH_SHA256_FOR_LINUX_AMD64"
    end
  end

  def install
    binary_name = "test-template-#{OS.kernel_name.downcase}-#{Hardware::CPU.arch}"
    bin.install binary_name => "test-template"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/test-template --version")
  end
end
